# frozen_string_literal: true

require 'selenium-webdriver'
require 'json'

# Generated by Selenium IDE
describe 'Correctdata' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end

  after(:each) do
    @driver.quit
  end

  it 'correct_data' do
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys '10'
    @driver.find_element(:name, 'commit').click
  end

  it 'incorrect_data' do
    @driver.get 'http://127.0.0.1:3000/'
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').clear
    @driver.find_element(:id, 'v1').send_keys 'as'
    @driver.find_element(:name, 'commit').click
  end

  it 'empty' do
    @driver.get 'http://127.0.0.1:3000/'
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').clear
    @driver.find_element(:id, 'v1').send_keys '1'
    @driver.find_element(:name, 'commit').click
  end
end
