# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Test1' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'test1' do
    @driver.get('http://127.0.0.1:3000/')
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('10')
    @driver.find_element(:name, 'commit').click
  end
end
